GRANT SELECT ON UP_PORTAL.WARGA_UMT TO FYP;
GRANT SELECT ON UP_PORTAL.FAKULTI TO FYP;
GRANT SELECT ON UP_PORTAL.JABATAN TO FYP;
GRANT SELECT ON UP_PORTAL.PROFIL_PELAJAR TO FYP;
GRANT SELECT ON UP_PORTAL.PROFIL_STAF TO FYP;

CREATE SYNONYM FYP.FAKULTI FOR UP_PORTAL.FAKULTI;
CREATE SYNONYM FYP.JABATAN FOR UP_PORTAL.JABATAN;
CREATE SYNONYM FYP.PROFIL_PELAJAR FOR UP_PORTAL.PROFIL_PELAJAR;
CREATE SYNONYM FYP.PROFIL_STAF FOR UP_PORTAL.PROFIL_STAF;
CREATE SYNONYM FYP.PROFIL_WARGA FOR UP_PORTAL.WARGA_UMT;
